const flex = { bonusMode: 'flex', bonus: {} }

export const EXTRA_RACES = {
  aasimar: { name: 'Aasimar', speed: 9, languages: ['Celestiale'], ...flex, book: 'Mostri del multiverso', traits: ['Resistenza necrotici e radianti', 'Luce interiore', 'Rivelazione celestiale'] },
  bugbear: { name: 'Bugbear', speed: 9, languages: ['Goblin'], ...flex, book: 'Mostri del multiverso', traits: ['Braccia lunghe', 'Sorpresa silenziosa', 'Potente'] },
  centauro: { name: 'Centauro', speed: 12, languages: ['Silvano'], ...flex, book: 'Mostri del multiverso', traits: ['Carica', 'Zoccoli', 'Equino'] },
  changeling: { name: 'Changeling', speed: 9, languages: ['due a scelta'], ...flex, book: 'Mostri del multiverso', traits: ['Cambia forma', 'Istinto da impostore'] },
  coboldo: { name: 'Coboldo', speed: 9, languages: ['Draconico'], ...flex, book: 'Mostri del multiverso', traits: ['Urlo di aiuto', 'Mente da gruppo', 'Visione nel buio'] },
  duergar: { name: 'Duergar', speed: 7.5, languages: ['Nanico'], ...flex, book: 'Mostri del multiverso', traits: ['Ingrandirsi', 'Invisibilità', 'Resiste all’illusione'] },
  eladrin: { name: 'Eladrin', speed: 9, languages: ['Elfico'], ...flex, book: 'Mostri del multiverso', traits: ['Passo fatato', 'Stagione che cambia'] },
  fatato: { name: 'Fatato', speed: 9, languages: ['Silvano'], ...flex, book: 'Mostri del multiverso', traits: ['Volo', 'Taglia piccola', 'Magia fatata'] },
  firbolg: { name: 'Firbolg', speed: 9, languages: ['Elfico', 'Gigante'], ...flex, book: 'Mostri del multiverso', traits: ['Passo nascosto', 'Parla con bestie e piante', 'Forza potente'] },
  githyanki: { name: 'Githyanki', speed: 9, languages: ['Gith'], ...flex, book: 'Mostri del multiverso', traits: ['Conoscenza astrale', 'Disciplina psichica'] },
  githzerai: { name: 'Githzerai', speed: 9, languages: ['Gith'], ...flex, book: 'Mostri del multiverso', traits: ['Difesa mentale', 'Disciplina psichica'] },
  gnomo_profondita: { name: 'Gnomo delle profondità', speed: 7.5, languages: ['Gnomesco', 'Sottocomune'], ...flex, book: 'Mostri del multiverso', traits: ['Visione nel buio superiore', 'Dono del sottosuolo'] },
  goblin: { name: 'Goblin', speed: 9, languages: ['Goblin'], ...flex, book: 'Mostri del multiverso', traits: ['Furia', 'Scatto per togliersi'] },
  goliath: { name: 'Goliath', speed: 9, languages: ['Gigante'], ...flex, book: 'Mostri del multiverso', traits: ['Resistenza della pietra', 'Corporatura potente', 'Competizione naturale'] },
  harengon: { name: 'Harengon', speed: 9, languages: ['Silvano'], ...flex, book: 'Mostri del multiverso', traits: ['Iniziativa da lepre', 'Balzo', 'Orecchie attente'] },
  hobgoblin: { name: 'Hobgoblin', speed: 9, languages: ['Goblin'], ...flex, book: 'Mostri del multiverso', traits: ['Dono del fato', 'Addestramento da compagnia'] },
  kenku: { name: 'Kenku', speed: 9, languages: ['due a scelta'], ...flex, book: 'Mostri del multiverso', traits: ['Imita suoni', 'Mente da esperto'] },
  leonin: { name: 'Leonin', speed: 10.5, languages: ['una a scelta'], ...flex, book: 'Mostri del multiverso', traits: ['Ruggito', 'Artigli', 'Vista acuta'] },
  lucertoloide: { name: 'Lucertoloide', speed: 9, languages: ['Draconico'], ...flex, book: 'Mostri del multiverso', traits: ['Morso', 'Trattiene il fiato', 'Nuota', 'Coda afferrante'] },
  minotauro: { name: 'Minotauro', speed: 9, languages: ['una a scelta'], ...flex, book: 'Mostri del multiverso', traits: ['Corna', 'Martellamento', 'Labirinto interiore'] },
  orco: { name: 'Orco', speed: 9, languages: ['Orchesco'], ...flex, book: 'Mostri del multiverso', traits: ['Scatto aggressivo', 'Resiste a un colpo mortale'] },
  owlin: { name: 'Owlin', speed: 9, languages: ['una a scelta'], ...flex, book: 'Mostri del multiverso', traits: ['Volo', 'Visione nel buio', 'Vista silenziosa'] },
  satiro: { name: 'Satiro', speed: 10.5, languages: ['Silvano'], ...flex, book: 'Mostri del multiverso', traits: ['Ariete', 'Resistenza magica', 'Mirthful leaps'] },
  elfo_mare: { name: 'Elfo del mare', speed: 9, languages: ['Elfico', 'Acquatico'], ...flex, book: 'Mostri del multiverso', traits: ['Nuota', 'Parla con le creature marine', 'Respiro d’acqua'] },
  shadar_kai: { name: 'Shadar-kai', speed: 9, languages: ['Elfico'], ...flex, book: 'Mostri del multiverso', traits: ['Benedizione della regina corvo', 'Resistenza necrotici'] },
  shifter: { name: 'Shifter', speed: 9, languages: ['una a scelta'], ...flex, book: 'Mostri del multiverso', traits: ['Trasformazione', 'Sensi acuti'] },
  tabaxi: { name: 'Tabaxi', speed: 9, languages: ['una a scelta'], ...flex, book: 'Mostri del multiverso', traits: ['Scatto felino', 'Artigli', 'Curiosità felina'] },
  tortle: { name: 'Tortle', speed: 9, languages: ['una a scelta'], ...flex, book: 'Mostri del multiverso', traits: ['Guscio come armatura', 'Trattiene il fiato', 'Artigli'] },
  tritone: { name: 'Tritone', speed: 9, languages: ['Primordiale'], ...flex, book: 'Mostri del multiverso', traits: ['Anfibio', 'Controlla aria e acqua', 'Messaggero degli abissi'] },
  yuan_ti: { name: 'Yuan-ti', speed: 9, languages: ['Abissale', 'Draconico'], ...flex, book: 'Mostri del multiverso', traits: ['Resistenza magica', 'Suggestione del veleno', 'Immunità al veleno'] },
}

export const EXTRA_CLASSES = {
  artefice: {
    name: 'Artefice',
    hd: 8,
    saves: ['cos', 'int'],
    skillCount: 2,
    skills: ['Arcano', 'Indagare', 'Medicina', 'Natura', 'Percezione', 'Rapidità di mano', 'Storia'],
    code: 'A',
    book: 'Tasha',
    caster: { ability: 'int', kind: 'prepared', cantrips: [2, 2, 3] },
    features: { 1: ['Infusione magica', 'Incantesimi'], 2: ['Oggetto replicato'], 3: ['Specialità'], 6: ['Maestria negli attrezzi'] },
  },
}

const sub = (key, name, book, level = 3) => ({ key, name, book, level })

export const SUBCLASSES = {
  barbaro: [
    sub('zelota', 'Zelota', 'Xanathar'),
    sub('bestia', 'Bestia', 'Tasha'),
    sub('magia_selvaggia', 'Magia selvaggia', 'Tasha'),
  ],
  bardo: [
    sub('spade', 'Spade', 'Xanathar'),
    sub('sussurri', 'Sussurri', 'Xanathar'),
    sub('creazione', 'Creazione', 'Tasha'),
    sub('eloquenza', 'Eloquenza', 'Tasha'),
  ],
  chierico: [
    sub('forgia', 'Forgia', 'Xanathar'),
    sub('tomba', 'Tomba', 'Xanathar'),
    sub('ordine', 'Ordine', 'Tasha'),
    sub('pace', 'Pace', 'Tasha'),
    sub('crepuscolo', 'Crepuscolo', 'Tasha'),
  ],
  druido: [
    sub('sogni', 'Sogni', 'Xanathar'),
    sub('pastore', 'Pastore', 'Xanathar'),
    sub('stelle', 'Stelle', 'Tasha'),
    sub('fuoco_selvaggio', 'Fuoco selvaggio', 'Tasha'),
  ],
  guerriero: [
    sub('cavaliere', 'Cavaliere', 'Xanathar'),
    sub('arciere_arcano', 'Arciere arcano', 'Xanathar'),
    sub('samurai', 'Samurai', 'Xanathar'),
    sub('cavaliere_runico', 'Cavaliere runico', 'Tasha'),
    sub('guerriero_psi', 'Guerriero psi', 'Tasha'),
  ],
  ladro: [
    sub('inquisitore', 'Inquisitore', 'Xanathar'),
    sub('scout', 'Scout', 'Xanathar'),
    sub('spadaccino', 'Spadaccino', 'Xanathar'),
    sub('fantasma', 'Fantasma', 'Tasha'),
    sub('lama_anima', 'Lama dell’anima', 'Tasha'),
  ],
  mago: [
    sub('guerra', 'Guerra', 'Xanathar'),
    sub('invenzione', 'Invenzione', 'Xanathar'),
    sub('canto_lame', 'Canto delle lame', 'Tasha'),
    sub('scribi', 'Ordine degli scribi', 'Tasha'),
  ],
  monaco: [
    sub('kensei', 'Kensei', 'Xanathar'),
    sub('anima_sole', 'Anima del sole', 'Xanathar'),
    sub('se_astrale', 'Sé astrale', 'Tasha'),
    sub('misericordia', 'Misericordia', 'Tasha'),
  ],
  paladino: [
    sub('conquista', 'Conquista', 'Xanathar'),
    sub('redenzione', 'Redenzione', 'Xanathar'),
    sub('gloria', 'Gloria', 'Tasha'),
    sub('sentinelle', 'Sentinelle', 'Tasha'),
  ],
  ranger: [
    sub('orizzonte', 'Viandante dell’orizzonte', 'Xanathar'),
    sub('ammazzamostri', 'Ammazzamostri', 'Xanathar'),
    sub('ombra', 'Predatore dell’ombra', 'Xanathar'),
    sub('fatato', 'Viandante fatato', 'Tasha'),
    sub('sciame', 'Custode dello sciame', 'Tasha'),
  ],
  stregone: [
    sub('anima_divina', 'Anima divina', 'Xanathar'),
    sub('ombra', 'Ombra', 'Xanathar'),
    sub('mente_aberrante', 'Mente aberrante', 'Tasha'),
    sub('anima_meccanica', 'Anima meccanica', 'Tasha'),
  ],
  warlock: [
    sub('celestiale', 'Celestiale', 'Xanathar'),
    sub('lama', 'Lama maledetta', 'Xanathar'),
    sub('abissale', 'Abissale', 'Tasha'),
    sub('genio', 'Genio', 'Tasha'),
  ],
  artefice: [
    sub('alchimista', 'Alchimista', 'Tasha'),
    sub('artigliere', 'Artigliere', 'Tasha'),
    sub('battaglia', 'Battaglia', 'Tasha'),
    sub('armaiolo', 'Armaiolo', 'Tasha'),
  ],
}

export const PATHS = [
  { key: 'mago_agonia', name: 'Mago dell’agonia', book: 'Nymphology', line: 'Consiglia adulti consenzienti sulla loro vita intima, con magia sociale.' },
  { key: 'ruffiano', name: 'Ruffiano mistico', book: 'Nymphology', line: 'Evoca, per un cliente adulto, il compagno che ha chiesto.' },
  { key: 'seduttore', name: 'Seduttore', book: 'Nymphology', line: 'Fascino magico verso chi è adulto e può rispondere di sì.' },
  { key: 'scrutatore', name: 'Scrutatore', book: 'Nymphology', line: 'Osserva a distanza persone adulte, senza entrare nelle loro stanze private da solo.' },
]

// Solo nomi e livello, testi originali riassunti: niente testo copyrightato dei manuali.
export const EXTRA_SPELLS = [
  // Nymphology · Magia blu (riassunti originali, adulti consenzienti)
  ['Velo di riservatezza', 1, 'N'],
  ['Patto tra adulti', 1, 'N'],
  ['Sguardo lontano', 2, 'N'],
  ['Compagno evocato', 3, 'N'],
  ['Bacio di quiete', 0, 'N'],
  ['Parola di consenso', 1, 'N'],
  ['Manto di intimità', 2, 'N'],
  ['Richiamo del desiderio', 3, 'N'],
  ['Occhio discreto', 2, 'N'],
  ['Legame di confidenza', 1, 'N'],
  // Xanathar / Tasha (nomi italiani di uso comune al tavolo)
  ['Tollere i morti', 0, 'CSW'],
  ['Assorbire gli elementi', 1, 'ADRSM'],
  ['Catapulta', 1, 'ASM'],
  ['Laccio', 1, 'DR'],
  ['Colpo di zefiro', 1, 'R'],
  ['Cerchio di potere', 5, 'CP'],
  ['Parola del potere: dolore', 7, 'BW'],
  ['Soffio del drago', 2, 'SM'],
  ['Lama d’ombra', 2, 'SMW'],
  ['Vento protettivo', 2, 'BDSM'],
  ['Frecce infuocate', 3, 'DRSM'],
  ['Passo tonante', 3, 'SM'],
  ['Trasferimento di vita', 3, 'C'],
  ['Evoca bestia', 2, 'DR'],
  ['Evoca non morti', 3, 'W'],
  ['Evoca elementale minore', 4, 'DM'],
  ['Evoca fatato', 3, 'DW'],
  ['Servitore minuscolo', 3, 'AM'],
  ['Intelletto del tarrasque', 8, 'M'],
  ['Muro di luce', 5, 'C'],
  ['Freccia psichica', 2, 'SM'],
  ['Scudo della fede', 1, 'CP'],
  ['Intuire le emozioni', 2, 'BW'],
  ['Invocare il duplicato', 4, 'MW'],
  ['Tempesta di grandine', 4, 'DM'],
  ['Spada di giustizia', 1, 'P'],
  ['Marchio del cacciatore', 1, 'R'],
  ['Benedizione del corvo', 1, 'W'],
  ['Danse macabre', 5, 'W'],
  ['Negare altrui', 7, 'MW'],
  ['Tormento mentale', 5, 'BW'],
  ['Sfera di combustione', 2, 'SM'],
  ['Lama verde fiammante', 0, 'AM'],
  ['Scoppio di bozzolo', 0, 'A'],
  ['Sfera magnetica', 2, 'A'],
  ['Flash of genius', 0, 'A'],
]

export const ARTIFICER_SPELLS = new Set([
  'Allarme', 'Cura ferite', 'Individuazione del magico', 'Identificare', 'Purificare cibo e bevande',
  'Santuario', 'Invisibilità', 'Levitazione', 'Ristorare inferiore', 'Protezione dal bene e dal male',
  'Dissolvi magie', 'Protezione dall’energia', 'Rimuovi maledizione', 'Volare', 'Riparare', 'Luce',
  'Messaggio', 'Prestidigitazione', 'Resistenza', 'Scudo', 'Camuffare se stesso', 'Nube di nebbia',
  'Scurovisione', 'Forma gassosa', 'Respirare sott’acqua', 'Lama verde fiammante', 'Scoppio di bozzolo',
  'Sfera magnetica', 'Servitore minuscolo', 'Assorbire gli elementi', 'Catapulta',
])
